spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:JAVA
    username: togatherWithJpa
    password: team1
    driver-class-name: oracle.jdbc.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


